FROM ubuntu:bionic
MAINTAINER giles@layerfree.net

ARG REPO=release

RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get -y install curl && \ 
    curl -s https://packagecloud.io/install/repositories/fdio/${REPO}/script.deb.sh |  bash && \
    apt-get -y install sudo apt-utils iproute2 iputils-ping iptables && \
    apt-get -y install sudo vpp vpp-plugins vpp-api-python vpp-lib vpp-dev && \
    apt-get -y clean all
