FROM vpp-container-fun/base
MAINTAINER mestery@mestery.com

COPY startstrongswan.sh /
COPY startvpp.sh /
COPY startup.conf /etc/vpp/startup.conf

RUN apt-get -y install strongswan tcpdump && \
    apt-get clean all

ENTRYPOINT /startvpp.sh
